### ISSUE TITLE
PayPal Express: update to checkout.js V4

### ISSUE THREAD

**Issue by misha-kotov** [magento/payment-improvements#19]
### Common Features
- Simplified Checkout flow.
- Customized buttons.
- Provides checkout.js javascript library.

### Description
The Express Checkout flow keeps the customer on merchant web page or mobile app throughout the entire checkout flow.
![image](https://user-images.githubusercontent.com/18131925/41549381-4919f33e-72eb-11e8-86e7-9fc745eeab3a.png)

1. When a customer clicks the PayPal button, merchant's app sets up the payment and begins the checkout in a PayPal popup window.
2. The customer logs into to PayPal. Or, if the customer previously enabled PayPal One Touch, they have logged in automatically.
3. The customer reviews and authorizes the payment.
4. PayPal returns control to merchant's app to finalize the payment. Merchant's app can optionally show the payment details on a confirmation page.

### Authorize Flow
PayPal Express provides different API: Client REST API, PayPal Payments REST API or Braintree SDKs.
This scenario describes how to perform authorization based on client and backend side REST API:
![image](https://user-images.githubusercontent.com/18131925/41549422-69dd6326-72eb-11e8-985f-d3018e9eb4a7.png)

Payments REST API can be used to perform capture, void, refund and other operations instead deprecated NVP API.

### Backward compatibility
- In general, transactions created via NVP API can be processed via REST API using Transaction ID.
- But merchant has to create an app to receive REST API credentials via developer.paypal.com.
- REST API credentials will be different from current NVP API credentials and should be set manually after upgrade.

### Backend integration approach for REST API
Use PHP SDK for PayPal RESTful APIs  https://github.com/paypal/PayPal-PHP-SDK
Use direct HTTP requests and responses formatted in JSON https://developer.paypal.com/docs/api/overview/

### Frontend integration approach - checkout.js v4
Details around the upgrade can be got from the following website: https://developer.paypal.com/docs/integration/direct/express-checkout/integration-jsv4/upgrade-integration/

In a case of Magento there two options:

1. Continue using NVP API (has been deprecated since 2017, don't need significant changes on the Magento backend)
2. Start using REST API as recommended by PayPal for new integrations (require implementation of PayPal Express Checkout from scratch using [Payment Provider Gateway](https://devdocs.magento.com/guides/v2.2/payments-integrations/payment-gateway/payment-gateway-intro.html) approach)

**Comment by joni-jones** [comment]
Already implemented by the core team.
