### ISSUE TITLE
Billing agreement management in Payment\Model\Method\Adapter  

### ISSUE THREAD

**Issue by vkublytskyi** [magento/payment-improvements#4]
Pain point by @rikterbeek:
> we need to extend the Adapter because it is missing the updateBillingAgreementStatus method.

**Comment by vkublytskyi** [comment]
@rikterbeek As `Payment\Model\Method\Adapter` is part of an API it is better to not change its interface. However new adapter with extended functionality may be introduced as part of the platform.

May you describe more detailed scenarios when this method is required for Adapter. A code example would be perfect.

**Comment by joni-jones** [comment]
This method is a part of `\Magento\Paypal\Model\Billing\Agreement\MethodInterface` but not of `\Magento\Payment\Model\MethodInterface`, why it should be in Adapter class?

**Comment by rikterbeek** [comment]
Hi @joni-jones,

Clear we are indeed relying on this one. With the vault implementation we can remove the dependency of the Billing Agreement.

Regards,
Rik
Adyen
