### ISSUE TITLE
Session quote replaced by quote_id_mask

### ISSUE THREAD

**Issue by vkublytskyi** [magento/payment-improvements#7]
Pain point by @rikterbeek:
> Braintree and other module replace the getting quote from session to quote_id_mask example: Magento\Braintree\Controller\Paypal\PlaceOrder

**Comment by vkublytskyi** [comment]
@rikterbeek please describe what issues caused by current behavior.

**Comment by rikterbeek** [comment]
@vkublytskyi Could not recall raising this issue so let's close it.
