### ISSUE TITLE
More params are needed for MethodInterface::canUseForCurrency

### ISSUE THREAD

**Issue by vkublytskyi** [magento/payment-improvements#9]
Pain point by @rikterbeek:
> To method canUseForCurrency() of intereface Magento\Payment\Model\MethodInterface add additional param

**Comment by vkublytskyi** [comment]
@rikterbeek please describe in which scenarios  `Magento\Payment\Model\MethodInterface:: canUseForCurrency` method requires more parameters than `$currencyCode` and what parameter you would like to add.

**Comment by rikterbeek** [comment]
@vkublytskyi could not recall raising this one so let's close it.
